### ISSUE TITLE
Support for logger object.

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-api-client#12]
While the API CLI client supported verbose output from Faraday to STDOUT, we need to support
Ruby client logger objects, so users can log Faraday verbose data to a place of their choosing.

this is enable when defining the Connection.handle

look at:
```
   faraday.response(:logger)
```

But we'd honor the logger objects at instantiation or request time.

```
   miq = ManageIQ::API::Client.new(:url => "http://localhost:3000",  :logger => <logger_object>, ...)
```

**Comment by Fryguy** [comment]
I started looking at this and part of the problem is that the connection context is not referenced by all of the various objects, so if it's defined at the Client level, then it can't be accessed anywhere.  @abellotti want to discuss with you how you want that to work.
