### ISSUE TITLE
Can't install manageiq-api-gem

### ISSUE THREAD

**Issue by arnikasky** [ManageIQ/manageiq-api-client#54]
Hi, guys
[root@srvc030 vmdb]# gem install manageiq-api-client
ERROR:  Could not find a valid gem 'manageiq-api-client' (>= 0) in any repository
ALso, can't find this gem on rubygems

**Comment by abellotti** [comment]
Hi @arnikasky we haven't published this gem to rubygems yet, we reference the github repo from the Gemfile/gemspec where we need it from.

**Comment by abellotti** [comment]
Hi @arnikasky,  @Fryguy pushed the gem to rubygems, you should be able to do the gem install now.

**Comment by arnikasky** [comment]
Hi, @abellotti and @Fryguy.
Thank you very much, I'll close issue.
