### ISSUE TITLE
Can't use gem with https

### ISSUE THREAD

**Issue by arnikasky** [ManageIQ/manageiq-api-client#60]
Hi, guys
I have ManageIQ producton server, where we must use https(not http).
But in this case I can't use manageiq-api-client gem, because ssl_verify should be false.
Please, add this option in manageiq-api-client gem.
Thank you very much!

**Comment by abellotti** [comment]
try adding the following parameter to the ManageIQ::API::Client.new call:

```
:ssl => {:verify => false}
```

Thanks

**Comment by abellotti** [comment]
@arnikasky just trying to find if this is still an issue.

**Comment by arnikasky** [comment]
Hi, all
Sorry for late answer, it works
